import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { AnimatedStars } from "./animated-stars";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "./theme-provider";

const inter = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "text-white")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          themes={[
            "dark"
          ]}
        >
          <AnimatedStars />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
